class Autogenerated {
  bool? success;
  String? mensaje;
  String? token;
  String? tokenExpira;
  String? nameRol;
  String? name;
  VwUsuario? vwUsuario;
  Persona? persona;

  Autogenerated(
      {this.success,
      this.mensaje,
      this.token,
      this.tokenExpira,
      this.nameRol,
      this.name,
      this.vwUsuario,
      this.persona});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    mensaje = json['mensaje'];
    token = json['token'];
    tokenExpira = json['tokenExpira'];
    nameRol = json['nameRol'];
    name = json['name'];
    vwUsuario = json['vwUsuario'] != null
        ? VwUsuario.fromJson(json['vwUsuario'])
        : null;
    persona =
        json['persona'] != null ? Persona.fromJson(json['persona']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['success'] = success;
    data['mensaje'] = mensaje;
    data['token'] = token;
    data['tokenExpira'] = tokenExpira;
    data['nameRol'] = nameRol;
    data['name'] = name;
    if (vwUsuario != null) {
      data['vwUsuario'] = vwUsuario!.toJson();
    }
    if (persona != null) {
      data['persona'] = persona!.toJson();
    }
    return data;
  }
}

class VwUsuario {
  String? usuario;
  Null? password;
  Null? email;
  Null? nombrePersona;
  Null? tipoPersona;
  Null? direccion;
  int? irol;
  Null? nombreRol;
  int? idUsuario;

  VwUsuario(
      {this.usuario,
      this.password,
      this.email,
      this.nombrePersona,
      this.tipoPersona,
      this.direccion,
      this.irol,
      this.nombreRol,
      this.idUsuario});

  VwUsuario.fromJson(Map<String, dynamic> json) {
    usuario = json['usuario'];
    password = json['password'];
    email = json['email'];
    nombrePersona = json['nombrePersona'];
    tipoPersona = json['tipoPersona'];
    direccion = json['direccion'];
    irol = json['irol'];
    nombreRol = json['nombreRol'];
    idUsuario = json['idUsuario'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['usuario'] = usuario;
    data['password'] = password;
    data['email'] = email;
    data['nombrePersona'] = nombrePersona;
    data['tipoPersona'] = this.tipoPersona;
    data['direccion'] = this.direccion;
    data['irol'] = this.irol;
    data['nombreRol'] = this.nombreRol;
    data['idUsuario'] = this.idUsuario;
    return data;
  }
}

class Persona {
  int? idPersona;
  String? nombrePersona;
  Null? tipoPersona;
  Null? tipoDocumento;
  Null? numeroDocumento;
  Null? telefono;
  Null? codigoUbigeo;
  Null? direccion;

  Persona(
      {this.idPersona,
      this.nombrePersona,
      this.tipoPersona,
      this.tipoDocumento,
      this.numeroDocumento,
      this.telefono,
      this.codigoUbigeo,
      this.direccion});

  Persona.fromJson(Map<String, dynamic> json) {
    idPersona = json['idPersona'];
    nombrePersona = json['nombrePersona'];
    tipoPersona = json['tipoPersona'];
    tipoDocumento = json['tipoDocumento'];
    numeroDocumento = json['numeroDocumento'];
    telefono = json['telefono'];
    codigoUbigeo = json['codigoUbigeo'];
    direccion = json['direccion'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['idPersona'] = this.idPersona;
    data['nombrePersona'] = this.nombrePersona;
    data['tipoPersona'] = this.tipoPersona;
    data['tipoDocumento'] = this.tipoDocumento;
    data['numeroDocumento'] = this.numeroDocumento;
    data['telefono'] = this.telefono;
    data['codigoUbigeo'] = this.codigoUbigeo;
    data['direccion'] = this.direccion;
    return data;
  }
}