class Autogenerated {
  String? usuario;
  String? password;

  Autogenerated({this.usuario, this.password});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    usuario = json['usuario'];
    password = json['password'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['usuario'] = this.usuario;
    data['password'] = this.password;
    return data;
  }
}